server:
  port: 8081

jwt:
  secret: "mySuperSecretKeyWhichIsAtLeast32BytesLongForHS256"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Callette?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: root
    password:

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG